version: '3.1'
services:
  django_prac:
    container_name: django_prac
    image: mmarnun/django:160
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST_BD: django_bd_prac
      USUARIO_BD: django
      CONTRASENA_BD: django
      NOMBRE_BD: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
      - 8082:8000
    depends_on:
      - django_bd_prac
  django_bd_prac:
    container_name: django_bd_prac
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    volumes:
      - django_bd_prac:/var/lib/mysql
volumes:
    django_bd_prac:
